### ISSUE TITLE
Lights Don't Turn On

### ISSUE THREAD

**Issue by tjcarney89** [learn-co-curriculum/ttt-7-valid-move#30]
The lights don't turn on for forking, passing tests, or submitting the lab.

**Comment by curiositypaths** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum.

This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
